export const HOME_GET_ACTIVITIES_SINCE_PENDING = 'Home/GET_ACTIVITIES_SINCE_PENDING';
export const HOME_GET_ACTIVITIES_SINCE_SUCCESS = 'Home/GET_ACTIVITIES_SINCE_SUCCESS';
export const HOME_GET_ACTIVITIES_SINCE_ERROR = 'Home/GET_ACTIVITIES_SINCE_ERROR';

export const MAP_GET_ACTIVITIES_SINCE_PENDING = 'Map/GET_ACTIVITIES_SINCE_PENDING';
export const MAP_GET_ACTIVITIES_SINCE_SUCCESS = 'Map/GET_ACTIVITIES_SINCE_SUCCESS';
export const MAP_GET_ACTIVITIES_SINCE_ERROR = 'Map/GET_ACTIVITIES_SINCE_ERROR';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';
