export const HOME_GET_ACTIVITIES_SINCE_PENDING = 'Home/GET_ACTIVITIES_SINCE_PENDING';
export const HOME_GET_ACTIVITIES_SINCE_SUCCESS = 'Home/GET_ACTIVITIES_SINCE_SUCCESS';
export const HOME_GET_ACTIVITIES_SINCE_ERROR = 'Home/GET_ACTIVITIES_SINCE_ERROR';

export const MAP_GET_ACTIVITIES_SINCE_PENDING = 'Map/GET_ACTIVITIES_SINCE_PENDING';
export const MAP_GET_ACTIVITIES_SINCE_SUCCESS = 'Map/GET_ACTIVITIES_SINCE_SUCCESS';
export const MAP_GET_ACTIVITIES_SINCE_ERROR = 'Map/GET_ACTIVITIES_SINCE_ERROR';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const PROFILE_LOAD_PENDING = 'Profile/PROFILE_LOAD_PENDING';
export const PROFILE_LOAD_SUCCESS = 'Profile/PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_ERROR = 'Profile/PROFILE_LOAD_ERROR';

export const EVENT_LOAD_PENDING = 'Event/EVENT_LOAD_PENDING';
export const EVENT_LOAD_SUCCESS = 'Event/EVENT_LOAD_SUCCESS';
export const EVENT_LOAD_ERROR = 'Event/EVENT_LOAD_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';
